### PR TITLE
Dark theme fixes 2023

### PR DESCRIPTION
**Pull request by Kenny2github**
Fixes issues [reported on the Community Portal](https://en.scratch-wiki.info/wiki/Scratch_Wiki_talk:Community_Portal/Not_Done#The_Wiki_now_has_%28beta%29_dark_theme%21) between 2022-03-15 and today, plus some that I noticed along the way.

### CODE REVIEW

**Review by jacob-g — COMMENTED** [review]
First thing I checked is that you only changed things under `.dark-theme`, so that looks good. Will actually do functional testing as time permits over the next few days.

**Review by jacob-g — CHANGES_REQUESTED** [review]
Reviewing these one at a time:
- no background on scratchblocks: PASS
- no border on pseudo-inputs: PASS
- fix preview warning being too bright: PARTIAL PASS (contrast is low with the dark-ish text on a dark background; this can be fixed at a later time if needed)
- CodeMirror: CANNOT TEST (issues getting it working on my local)
- WikiEditor help table: FAIL (open special characters, still shows dark on dark)
- search results being white: PASS
- OOUI fixes: PASS
- pending interference: CANNOT REPRODUCE (not sure how to trigger this behavior at all)
- page history: FAIL (while the two most recent items avoid a light background, some of the text is dark on dark)
- VisualEditor fixes: PARTIAL PASS (you are missing one thing, if you open a dropdown in the toolbar that's still light on light)
- file metadata table: PASS
- selection in CodeMirror: CANNOT TEST (can't get CodeMirror working)
- captions being invisible: CANNOT TEST (cannot reproduce on the old theme)

**Comment by jacob-g** [comment]
Update since I have CodeMirror working:
- CodeMirror gutter: PASS
- CodeMirror selection: PASS

**Comment by jacob-g** [comment]
Update when I got pending to work (using Special:Contributions and searching a username):
* pending interference: PASS

**Comment by jacob-g** [comment]
Another update now that I have looked more closely at the WikiEditor help table:
- WikiEditor help table: PASS (special characters still is dark on dark, but can be fixed at a later time)

**Comment by jacob-g** [comment]
Another update now that I have been informed that the caption invisibility issue is in template documentation:
- captions being invisible: PASS

**Comment by Kenny2github** [comment]
> fix preview warning being too bright: PARTIAL PASS (contrast is low with the dark-ish text on a dark background; this can be fixed at a later time if needed)

contrast ratio passes WCAG AAA standard
image of actual preview warning

Not sure how much more contrast you need?

**Comment by Kenny2github** [comment]
Addressed review comments and also fixed a swath of issues I noticed while doing so

**Comment by jacob-g** [comment]
For previous issues identified:
fix preview warning being too bright: PASS
VisualEditor fixes: PASS

This addresses all issues from my earlier review. Now I will proceed reviewing the _new_ fixes.

**Comment by jacob-g** [comment]
Results:
message box styling: CANNOT TEST (not sure what the original issue is)
special characters: PASS
VisualEditor/OOUI issues: PASS
OOUI borders: CANNOT TEST (not sure what the original issue is)
preferences: CANNOT TEST (not sure what the original issue is)
Recent Changes: CANNOT TEST (not sure what the original issue is)
VisualEditor pop-ups: PASS
Echo issues: PASS
reference highlighting: PASS

**Comment by Kenny2github** [comment]
Original issues:
- message box styling: the "change your password, it's too simple" warning on login was badly styled. It seems that newer versions of MW use a more MW-specific class, rendering the original fix ineffective, so I added the one used in that warning and extrapolated to the other classes.
- OOUI borders: generally there was inconsistency between some buttons/input elements/etc. having dark or light borders, especially in the VisualEditor gallery modal and Special:Log/Special:Contributions. I made them all light (as far as I can tell).
- preferences: the Echo notification settings table's even-numbered rows were light on light. The timezone input was also bad.
- Recent Changes: one button had a doubly thick border, the legend flashbanged during loading, and the buttons in the bottom right of the filter panel were misaligned with the rest of the bottom buttons.

**Comment by jacob-g** [comment]
message box styling: PASS
OOUI borders: PARTIAL PASS - you introduced a regression with the dropdown arrow (this problem isn't present on the pre-fix version)
image
preferences: PASS
Recent Changes: PASS

**Comment by Kenny2github** [comment]
Tag filter drop-down arrow is not a blocker (it will take significantly more effort and is not a dark-on-dark/light-on-light issue) so it can go in the next batch of fixes

**Review by jacob-g — APPROVED** [review]
All outstanding issues but one have been fixed, and the remaining one is not a blocker and has been noted for future fixing.

**Pull request merged**
