### PR TITLE
Hotfix mobile design

### PR DESCRIPTION
**Pull request by Kenny2github**
Change to use a button after all

+ Add CREDITS file for proper attribution
+ Add new images
* Change profile link text to an image on smaller screens, and remove the dropdown icon then
* Add hamburger button to toggle sidebar

Visit https://hkugawiki.ddns.net/test/BBCode_Sandbox for a demo of changes.

### CODE REVIEW

**Comment by apple502j** [comment]
LGTM

**Comment by mtwoll** [comment]
Sorry, I could not test, because https://hkugawiki.ddns.net/test/BBCode_Sandbox does not work for me at the moment

**Comment by Kenny2github** [comment]
@mtwoll what is the problem?

**Comment by apple502j** [comment]
Found one problem:
 strange blue

**Comment by mtwoll** [comment]
I now tested https://hkugawiki.ddns.net/test/BBCode_Sandbox at my mobile and the new top left browser button seems to work and is a big advantage over the old swipe-style menu.

When calling https://hkugawiki.ddns.net/test/BBCode_Sandbox I get the Error: from my company network I got following error, but that may be caused by our firewall:

Diese Website ist nicht erreichbar
Die Antwort von hkugawiki.ddns.net hat zu lange gedauert.
Versuchen Sie Folgendes:

Verbindung prüfen
Proxy und Firewall prüfen
Windows-Netzwerkdiagnose ausführen
ERR_CONNECTION_TIMED_OUT

**Comment by Kenny2github** [comment]
Okay, I'll take that as approval. The blue footer thing can be fixed later.

**Pull request merged**
