### PR TITLE
No wrap for dropdown box

### PR DESCRIPTION
**Pull request by apple502j**
Thanks for NYCDOT and asqwde who reported this bug.

I tested this code with Stylish and it worked well.

### CODE REVIEW

**Comment by apple502j** [comment]
Many lines
So far the dropdown is like this

One line an option
After using this patch

**Comment by Kenny2github** [comment]
I don't have this problem?
image

**Comment by apple502j** [comment]
Firefox 59.0.1 Windows 7 Home Premium 64bit What's your browser?

**Comment by Kenny2github** [comment]
Latest Chrome Windows 8.1 64-bit

**Comment by apple502j** [comment]
Chrome 65.0.3325.181 OK
but Firefox is not?

**Comment by Kenny2github** [comment]
I'm testing IE (ugh) and there's a syntax error in the JS :P

**Comment by apple502j** [comment]
Edge is like Firefox

**Comment by Kenny2github** [comment]
Not Edge, IE. Anyway, reproduced on latest IE on Windows 8:
image
Confirmed that `white-space: nowrap` is working:
image

**Pull request merged**
