### PR TITLE
Fixed IE nested media queries bug

### PR DESCRIPTION
**Pull request by Ascor8522**
- Moved all css files to a new subfolder
- Made new css for specific mediaqueries as described in [the MediaWiki ResourceLoader tutorial](https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#Media_queries)

This should fix https://github.com/InternationalScratchWiki/ScratchWikiSkin2/issues/53

### CODE REVIEW

**Review by ahmetlii — APPROVED** [review]

**Review by ahmetlii — APPROVED** [review]

**Comment by ahmetlii** [comment]
> * Moved all css files to a new subfolder
> * Made new css for specific mediaqueries as described in [the MediaWiki ResourceLoader tutorial](https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#Media_queries)
> 
> This should fix #53



> * Moved all css files to a new subfolder
> * Made new css for specific mediaqueries as described in [the MediaWiki ResourceLoader tutorial](https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#Media_queries)
> 
> This should fix #53

it's still not solving, plus I don't think that we should really support IE since it's not getting updates from Microsoft and encourages users to use Edge.
the problem

**Comment by Ascor8522** [comment]
I have no idea how you did your tests but on my instance it's working great.

image

**Comment by Ascor8522** [comment]
> it's still not solving, plus I don't think that we should really support IE since it's not getting updates from Microsoft and encourages users to use Edge.

While I 100% agree with you, I believe it's an easy fix, plus  it's actually the proper way to do it (since MediaWiki offers a built-in way to load css with media queries).

https://github.com/InternationalScratchWiki/ScratchWikiSkin2/issues/53#issuecomment-706602315

**Comment by ahmetlii** [comment]
> I have no idea how you did your tests but on my instance it's working great.
> 
> image

I accidentally fetched master, that's why.

**Review by Kenny2github — APPROVED** [review]
This is going to make pulling dark theme hell, but this tests fine. In it goes!

**Pull request merged**
